description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/about" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: vipul_sharma
github_username: vipul-sharma20

remote_theme: "mmistakes/minimal-mistakes"
# theme: minimal-mistakes-jekyll

# Build settings
minimal_mistakes_skin: "air"

# theme: minima
plugins:
  - jekyll-include-cache
  - jekyll-paginate


locale                   : "en-US"
title                    : "Vipul Sharma's Blog"
email                    : vipul.sharma20@gmail.com
title_separator          : "-"
# subtitle                 : ""
name                     : "Vipul Sharma"
description              : "Vipul Sharma's Blog"
url                      : "https://vipul.xyz"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "vipul-sharma20/blog"
logo                     : "/assets/images/logo.png"
# teaser                   : "/assets/images/vim.jpg"
masthead_title           : " "
breadcrumbs              : false
search                   : true

paginate: 5
paginate_path: /page:num/
include                  : ["_pages", "_portfolio", "_includes", "_journal", "_printing"]

author:
  name: "Vipul Sharma"
  avatar: "/assets/images/me.jpg"
  bio: "Engineer at Skit.ai" # Note: Markdown is allowed
  location: "India"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/vipul-sharma20"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/vipul20/"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/vipul.py"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/vipul_sharma"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/vipul-sharma20"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/vipul20/"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/vipul.py"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/vipul_sharma"

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
  journal:
    output: true
    permalink: /:collection/:path/
  printing:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true

  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true

  # _printing
  - scope:
      path: ""
      type: printing
    values:
      layout: single
      author_profile: true
      share: true

  # _journal
  - scope:
      path: ""
      type: journal
    values:
      layout: single
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
