import MarkdownIt from 'markdown-it';
import { createHighlighter, type Highlighter } from 'shiki';

let highlighterPromise: Promise<Highlighter> | null = null;

function getHighlighter(): Promise<Highlighter> {
  if (!highlighterPromise) {
    highlighterPromise = createHighlighter({
      themes: ['github-light'],
      langs: [
        'javascript', 'typescript', 'python', 'bash', 'shell',
        'json', 'yaml', 'html', 'css', 'markdown', 'ruby',
        'go', 'rust', 'sql', 'dockerfile', 'plaintext',
      ],
    });
  }
  return highlighterPromise;
}

function preprocessJekyllSyntax(content: string): string {
  // Replace Jekyll/Liquid template variables
  content = content.replace(/\{\{\s*site\.baseurl\s*\}\}/g, '');
  content = content.replace(/\{\{\s*site\.url\s*\}\}/g, '');
  return content;
}

function preprocessJekyllIncludes(content: string): string {
  // Convert {% include article-image.html src="..." alt="..." position="..." caption="..." %}
  content = content.replace(
    /\{%\s*include\s+article-image\.html\s+(.*?)%\}/g,
    (_match: string, attrs: string) => {
      const src = attrs.match(/src="([^"]*)"/)?.[1] || '';
      const alt = attrs.match(/alt="([^"]*)"/)?.[1] || '';
      const position = attrs.match(/position="([^"]*)"/)?.[1] || 'center';
      const caption = attrs.match(/caption="([^"]*)"/)?.[1] || '';
      const figcaption = caption ? `\n  <figcaption>${caption}</figcaption>` : '';
      return `<figure class="article-image article-image-${position}">
  <img src="${src}" alt="${alt}" loading="lazy" />${figcaption}
</figure>`;
    }
  );

  // Convert {% include image.html url="..." alt="..." size="..." caption="..." %}
  content = content.replace(
    /\{%\s*include\s+image\.html\s+(.*?)%\}/g,
    (_match: string, attrs: string) => {
      const url = attrs.match(/url="([^"]*)"/)?.[1] || '';
      const alt = attrs.match(/alt="([^"]*)"/)?.[1] || '';
      const size = attrs.match(/size="([^"]*)"/)?.[1] || 'center';
      const caption = attrs.match(/caption="([^"]*)"/)?.[1] || '';
      const positionClass = size === 'small' ? 'small' : size === 'full' ? 'full' : 'center';
      const figcaption = caption ? `\n  <figcaption>${caption}</figcaption>` : '';
      return `<figure class="article-image article-image-${positionClass}">
  <img src="${url}" alt="${alt}" loading="lazy" />${figcaption}
</figure>`;
    }
  );

  return content;
}

/**
 * Match the IDs generated by Kramdown, which rendered the site before the
 * Next.js migration. Keeping the same algorithm preserves existing section
 * links to older posts.
 */
function createHeadingId(rawHeading: string, usedIds: Map<string, number>): string {
  let id = rawHeading
    .replace(/^[^a-zA-Z]+/, '')
    .replace(/[^a-zA-Z0-9 -]/g, '')
    .replace(/ /g, '-')
    .toLowerCase();

  if (!id) id = 'section';

  const previousCount = usedIds.get(id);
  if (previousCount === undefined) {
    usedIds.set(id, 0);
  } else {
    const nextCount = previousCount + 1;
    usedIds.set(id, nextCount);
    id = `${id}-${nextCount}`;
  }

  return id;
}

function addHeadingPermalinks(html: string): string {
  return html.replace(
    /<h([1-6])([^>]*)>([\s\S]*?)<\/h\1>/gi,
    (heading, level: string, attrs: string, content: string) => {
      const idMatch = attrs.match(/\sid=(?:"([^"]*)"|'([^']*)'|([^\s>]+))/i);
      const id = idMatch?.[1] ?? idMatch?.[2] ?? idMatch?.[3];

      if (!id || /\bheading-permalink\b/.test(content)) return heading;

      return `<h${level}${attrs}>${content}<a class="heading-permalink" href="#${id}" aria-label="Permalink to this section" title="Permalink"><span aria-hidden="true">#</span></a></h${level}>`;
    },
  );
}

export async function renderMarkdown(content: string): Promise<string> {
  const highlighter = await getHighlighter();

  // Pre-process Jekyll syntax before markdown rendering
  content = preprocessJekyllSyntax(content);
  content = preprocessJekyllIncludes(content);

  const md = new MarkdownIt({
    html: true,
    linkify: true,
    typographer: true,
  });

  // Enable tables (built-in)
  md.enable('table');

  // markdown-it does not assign IDs to headings by default. Generate stable
  // IDs during server rendering so fragment URLs work even before hydration.
  const usedHeadingIds = new Map<string, number>();
  const defaultHeadingOpen = md.renderer.rules.heading_open;
  md.renderer.rules.heading_open = (tokens, idx, options, env, self) => {
    const inlineToken = tokens[idx + 1];
    tokens[idx].attrSet('id', createHeadingId(inlineToken?.content || '', usedHeadingIds));

    return defaultHeadingOpen
      ? defaultHeadingOpen(tokens, idx, options, env, self)
      : self.renderToken(tokens, idx, options);
  };

  // Wrap each table in a scroll container so wide tables scroll horizontally
  // within their own box instead of forcing the whole page to scroll.
  md.renderer.rules.table_open = () => '<div class="table-wrapper"><table>\n';
  md.renderer.rules.table_close = () => '</table></div>\n';

  // Custom code block renderer using Shiki
  md.options.highlight = (code: string, lang: string) => {
    const language = lang || 'plaintext';
    try {
      const loadedLangs = highlighter.getLoadedLanguages();
      if (loadedLangs.includes(language as never)) {
        const highlighted = highlighter.codeToHtml(code, {
          lang: language,
          theme: 'github-light',
        });
        // Strip Shiki's inline background/color on the <pre> so the code block
        // inherits the site's themed card background from globals.css instead of
        // Shiki's hard-coded white. Token colors (on the spans) are left intact.
        return highlighted.replace(
          /(<pre class="shiki[^"]*")[^>]*style="[^"]*"/,
          '$1',
        );
      }
    } catch {
      // fall through to default
    }
    // Fallback: escape and wrap in pre/code
    const escaped = md.utils.escapeHtml(code);
    return `<pre><code class="language-${language}">${escaped}</code></pre>`;
  };

  let html = md.render(content);

  // GitHub-style callouts: > [!NOTE], > [!TIP], > [!IMPORTANT], > [!WARNING], > [!CAUTION]
  // markdown-it renders these as <blockquote>\n<p>[!TYPE]\ncontent</p>\n</blockquote>
  const ghCalloutMap: Record<string, string> = {
    'NOTE': 'notice-info',
    'TIP': 'notice-success',
    'IMPORTANT': 'notice',
    'WARNING': 'notice-warning',
    'CAUTION': 'notice-danger',
  };

  html = html.replace(
    /<blockquote>\s*\n?\s*<p>\[!(NOTE|TIP|IMPORTANT|WARNING|CAUTION)\]\s*\n?([\s\S]*?)<\/p>\s*\n?\s*<\/blockquote>/g,
    (_, type: string, content: string) => {
      const className = ghCalloutMap[type] || 'notice';
      const label = type.charAt(0) + type.slice(1).toLowerCase();
      return `<div class="${className}"><p class="callout-title">${label}</p><p>${content.trim()}</p></div>`;
    }
  );

  // Kramdown-style notice blocks: {: .notice--info} (backward compat)
  // Note: typographer converts -- to – (en dash), so match both
  // Case 1: {: .notice} appears AFTER the closing tag
  html = html.replace(
    /(<(?:p|blockquote|div|ul|ol)[^>]*>[\s\S]*?<\/(?:p|blockquote|div|ul|ol)>)\s*\n?\{:\s*\.notice(?:(?:--|–)(info|success|warning|danger))?\s*\}/g,
    (_, element: string, type: string) => {
      const className = type ? `notice-${type}` : 'notice';
      return `<div class="${className}">${element}</div>`;
    }
  );
  // Case 2: {: .notice} is INSIDE the <p> tag (markdown-it inlines it)
  // Use [^]* that won't cross </p> boundaries
  html = html.replace(
    /<p>([^<]*(?:<(?!\/p>)[^<]*)*)\n?\{:\s*\.notice(?:(?:--|–)(info|success|warning|danger))?\s*\}<\/p>/g,
    (_, content: string, type: string) => {
      const className = type ? `notice-${type}` : 'notice';
      return `<div class="${className}"><p>${content.trim()}</p></div>`;
    }
  );

  // Add a clickable permalink to Markdown headings and to hand-written HTML
  // headings that already have an ID.
  return addHeadingPermalinks(html);
}
